import type { SkillCategory } from "@/lib/types";

export const skillsData: SkillCategory[] = [
  {
    name: "Frontend Development",
    items: [
      { name: "React.js" },
      { name: "Next.js" },
      { name: "Next.js App Router" },
      { name: "Server Components" },
      { name: "SSR & SSG" },
      { name: "API Routes" },
      { name: "Angular" },
      { name: "Vue.js" },
      { name: "TypeScript" },
      { name: "JavaScript (ES6+)" },
      { name: "HTML5 & CSS3" },
      { name: "Tailwind CSS" },
      { name: "ShadCN UI" },
      { name: "Material UI" },
      { name: "Ant Design" },
      { name: "Responsive Design" },
      { name: "Redux Toolkit" },
      { name: "Zustand" },
      { name: "React Query" },
      { name: "Framer Motion" },
    ],
  },
  {
    name: "Backend Development",
    items: [
      { name: "Node.js" },
      { name: "Express.js" },
      { name: "REST API Development" },
      { name: "Authentication (JWT, OAuth)" },
      { name: "Serverless Functions" },
      { name: "Ruby on Rails" },
      { name: "WebSockets / Socket.io" },
      { name: "Real-Time Applications" },
    ],
  },
  {
    name: "AI Development",
    items: [
      { name: "OpenAI API Integration" },
      { name: "ChatGPT API Integration" },
      { name: "AI Chatbot Implementation" },
      { name: "AI Features Integration in Web Applications" },
      { name: "AI-powered SaaS Features" },
      { name: "API Integration & Response Handling" },
      { name: "Custom AI UI Development (Chat Interfaces)" },
      { name: "Claude AI" },
      { name: "Cursor AI Editor" },
      { name: "Antigravity AI" },
    ],
  },
  {
    name: "Database Management",
    items: [
      { name: "MongoDB" },
      { name: "PostgreSQL" },
      { name: "MySQL" },
      { name: "Prisma ORM" },
    ],
  },
  {
    name: "Payment Integration",
    items: [
      { name: "Stripe Integration" },
      { name: "Stripe Checkout" },
      { name: "Stripe Subscriptions" },
      { name: "Webhook Handling" },
      { name: "Payment Flow Implementation" },
      { name: "PayPal Integration" },
    ],
  },
  {
    name: "Testing & QA",
    items: [
      { name: "Jest" },
      { name: "React Testing Library" },
      { name: "Cypress" },
    ],
  },
  {
    name: "Tools & DevOps",
    items: [
      { name: "Git" },
      { name: "GitHub" },
      { name: "GitHub Actions (CI/CD)" },
      { name: "Docker" },
      { name: "Deployment (Vercel, Netlify, Render)" },
      { name: "Domain & Hosting Setup" },
      { name: "Postman" },
      { name: "VS Code" },
      { name: "Figma" },
      { name: "ClickUp" },
      { name: "Jira" },
      { name: "Trello" },
      { name: "Linux & Terminal / CLI" },
      { name: "GitHub Copilot" },
      { name: "OpenAI Playground" },
    ],
  },
];